/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author osval
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mesasPanel = new Control.PanelRound();
        mesa1P = new Control.PanelRound();
        mesa2P = new Control.PanelRound();
        mesa3P = new Control.PanelRound();
        mesa4P = new Control.PanelRound();
        mesa5P = new Control.PanelRound();
        mesa6P = new Control.PanelRound();
        mesa7P = new Control.PanelRound();
        mesa8P = new Control.PanelRound();
        mesa9P = new Control.PanelRound();
        mesa2 = new javax.swing.JLabel();
        mesa1 = new javax.swing.JLabel();
        mesa3 = new javax.swing.JLabel();
        mesa4 = new javax.swing.JLabel();
        mesa5 = new javax.swing.JLabel();
        mesa6 = new javax.swing.JLabel();
        mesa7 = new javax.swing.JLabel();
        mesa8 = new javax.swing.JLabel();
        mesa9 = new javax.swing.JLabel();
        tituloPanel = new Control.PanelRound();
        Titulo = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        confirmarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        fechaReservaCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroPersonasTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        horaReservaCB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombreClienteTxt = new javax.swing.JTextField();
        estadoTxt = new javax.swing.JTextField();
        costoTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mesasPanel.setBackground(new java.awt.Color(51, 51, 51));
        mesasPanel.setForeground(new java.awt.Color(102, 102, 102));
        mesasPanel.setRoundBottomLeft(50);
        mesasPanel.setRoundBottomRight(50);
        mesasPanel.setRoundTopLeft(50);
        mesasPanel.setRoundTopRight(50);

        mesa1P.setBackground(new java.awt.Color(153, 255, 153));
        mesa1P.setRoundBottomLeft(100);
        mesa1P.setRoundBottomRight(100);
        mesa1P.setRoundTopLeft(100);
        mesa1P.setRoundTopRight(100);

        javax.swing.GroupLayout mesa1PLayout = new javax.swing.GroupLayout(mesa1P);
        mesa1P.setLayout(mesa1PLayout);
        mesa1PLayout.setHorizontalGroup(
            mesa1PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mesa1PLayout.setVerticalGroup(
            mesa1PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mesa2P.setBackground(new java.awt.Color(153, 255, 153));
        mesa2P.setRoundBottomLeft(100);
        mesa2P.setRoundBottomRight(100);
        mesa2P.setRoundTopLeft(100);
        mesa2P.setRoundTopRight(100);

        javax.swing.GroupLayout mesa2PLayout = new javax.swing.GroupLayout(mesa2P);
        mesa2P.setLayout(mesa2PLayout);
        mesa2PLayout.setHorizontalGroup(
            mesa2PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mesa2PLayout.setVerticalGroup(
            mesa2PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mesa3P.setBackground(new java.awt.Color(153, 255, 153));
        mesa3P.setRoundBottomLeft(100);
        mesa3P.setRoundBottomRight(100);
        mesa3P.setRoundTopLeft(100);
        mesa3P.setRoundTopRight(100);

        javax.swing.GroupLayout mesa3PLayout = new javax.swing.GroupLayout(mesa3P);
        mesa3P.setLayout(mesa3PLayout);
        mesa3PLayout.setHorizontalGroup(
            mesa3PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mesa3PLayout.setVerticalGroup(
            mesa3PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mesa4P.setBackground(new java.awt.Color(153, 255, 153));
        mesa4P.setRoundBottomLeft(100);
        mesa4P.setRoundBottomRight(100);
        mesa4P.setRoundTopLeft(100);
        mesa4P.setRoundTopRight(100);

        javax.swing.GroupLayout mesa4PLayout = new javax.swing.GroupLayout(mesa4P);
        mesa4P.setLayout(mesa4PLayout);
        mesa4PLayout.setHorizontalGroup(
            mesa4PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mesa4PLayout.setVerticalGroup(
            mesa4PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mesa5P.setBackground(new java.awt.Color(153, 255, 153));
        mesa5P.setRoundBottomLeft(100);
        mesa5P.setRoundBottomRight(100);
        mesa5P.setRoundTopLeft(100);
        mesa5P.setRoundTopRight(100);

        javax.swing.GroupLayout mesa5PLayout = new javax.swing.GroupLayout(mesa5P);
        mesa5P.setLayout(mesa5PLayout);
        mesa5PLayout.setHorizontalGroup(
            mesa5PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mesa5PLayout.setVerticalGroup(
            mesa5PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mesa6P.setBackground(new java.awt.Color(153, 255, 153));
        mesa6P.setRoundBottomLeft(100);
        mesa6P.setRoundBottomRight(100);
        mesa6P.setRoundTopLeft(100);
        mesa6P.setRoundTopRight(100);

        javax.swing.GroupLayout mesa6PLayout = new javax.swing.GroupLayout(mesa6P);
        mesa6P.setLayout(mesa6PLayout);
        mesa6PLayout.setHorizontalGroup(
            mesa6PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mesa6PLayout.setVerticalGroup(
            mesa6PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mesa7P.setBackground(new java.awt.Color(153, 255, 153));
        mesa7P.setRoundBottomLeft(100);
        mesa7P.setRoundBottomRight(100);
        mesa7P.setRoundTopLeft(100);
        mesa7P.setRoundTopRight(100);

        javax.swing.GroupLayout mesa7PLayout = new javax.swing.GroupLayout(mesa7P);
        mesa7P.setLayout(mesa7PLayout);
        mesa7PLayout.setHorizontalGroup(
            mesa7PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mesa7PLayout.setVerticalGroup(
            mesa7PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mesa8P.setBackground(new java.awt.Color(153, 255, 153));
        mesa8P.setRoundBottomLeft(100);
        mesa8P.setRoundBottomRight(100);
        mesa8P.setRoundTopLeft(100);
        mesa8P.setRoundTopRight(100);

        javax.swing.GroupLayout mesa8PLayout = new javax.swing.GroupLayout(mesa8P);
        mesa8P.setLayout(mesa8PLayout);
        mesa8PLayout.setHorizontalGroup(
            mesa8PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mesa8PLayout.setVerticalGroup(
            mesa8PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mesa9P.setBackground(new java.awt.Color(153, 255, 153));
        mesa9P.setRoundBottomLeft(100);
        mesa9P.setRoundBottomRight(100);
        mesa9P.setRoundTopLeft(100);
        mesa9P.setRoundTopRight(100);

        javax.swing.GroupLayout mesa9PLayout = new javax.swing.GroupLayout(mesa9P);
        mesa9P.setLayout(mesa9PLayout);
        mesa9PLayout.setHorizontalGroup(
            mesa9PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mesa9PLayout.setVerticalGroup(
            mesa9PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mesa2.setBackground(new java.awt.Color(255, 255, 255));
        mesa2.setForeground(new java.awt.Color(255, 255, 255));
        mesa2.setText("MESA 2");

        mesa1.setBackground(new java.awt.Color(255, 255, 255));
        mesa1.setForeground(new java.awt.Color(255, 255, 255));
        mesa1.setText("MESA 1");

        mesa3.setBackground(new java.awt.Color(255, 255, 255));
        mesa3.setForeground(new java.awt.Color(255, 255, 255));
        mesa3.setText("MESA 3");

        mesa4.setBackground(new java.awt.Color(255, 255, 255));
        mesa4.setForeground(new java.awt.Color(255, 255, 255));
        mesa4.setText("MESA 4");

        mesa5.setBackground(new java.awt.Color(255, 255, 255));
        mesa5.setForeground(new java.awt.Color(255, 255, 255));
        mesa5.setText("MESA 5");

        mesa6.setBackground(new java.awt.Color(255, 255, 255));
        mesa6.setForeground(new java.awt.Color(255, 255, 255));
        mesa6.setText("MESA 6");

        mesa7.setBackground(new java.awt.Color(255, 255, 255));
        mesa7.setForeground(new java.awt.Color(255, 255, 255));
        mesa7.setText("MESA 7");

        mesa8.setBackground(new java.awt.Color(255, 255, 255));
        mesa8.setForeground(new java.awt.Color(255, 255, 255));
        mesa8.setText("MESA 8");

        mesa9.setBackground(new java.awt.Color(255, 255, 255));
        mesa9.setForeground(new java.awt.Color(255, 255, 255));
        mesa9.setText("MESA 9");

        javax.swing.GroupLayout mesasPanelLayout = new javax.swing.GroupLayout(mesasPanel);
        mesasPanel.setLayout(mesasPanelLayout);
        mesasPanelLayout.setHorizontalGroup(
            mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mesasPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mesa7P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa4P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa1P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesa2P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa5P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa8P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesa9P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa6P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa3P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(mesasPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(mesa1)
                .addGap(142, 142, 142)
                .addComponent(mesa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mesa3)
                .addGap(87, 87, 87))
            .addGroup(mesasPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(mesa4)
                .addGap(142, 142, 142)
                .addComponent(mesa5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mesa6)
                .addGap(87, 87, 87))
            .addGroup(mesasPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(mesa7)
                .addGap(142, 142, 142)
                .addComponent(mesa8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mesa9)
                .addGap(87, 87, 87))
        );
        mesasPanelLayout.setVerticalGroup(
            mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mesasPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesa3P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa2P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa1P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesa2)
                    .addComponent(mesa1)
                    .addComponent(mesa3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mesa4P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa5P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa6P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mesa5)
                        .addComponent(mesa6))
                    .addComponent(mesa4))
                .addGap(62, 62, 62)
                .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mesa7P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa8P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa9P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mesasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mesa8)
                        .addComponent(mesa9))
                    .addComponent(mesa7))
                .addGap(29, 29, 29))
        );

        getContentPane().add(mesasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 46, 570, -1));

        tituloPanel.setBackground(new java.awt.Color(102, 102, 102));
        tituloPanel.setRoundBottomLeft(50);
        tituloPanel.setRoundBottomRight(50);
        tituloPanel.setRoundTopLeft(50);
        tituloPanel.setRoundTopRight(50);

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Reservaciones");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(Titulo)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Titulo)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 46, 480, 110));

        Fondo.setBackground(new java.awt.Color(22, 22, 22));
        Fondo.setForeground(new java.awt.Color(51, 51, 51));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmarBtn.setBackground(new java.awt.Color(102, 102, 102));
        confirmarBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        confirmarBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmarBtn.setText("Confirmar");
        confirmarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBtnActionPerformed(evt);
            }
        });
        Fondo.add(confirmarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, 140, 50));

        cancelarBtn.setBackground(new java.awt.Color(102, 102, 102));
        cancelarBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cancelarBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        Fondo.add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 140, 50));

        fechaReservaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(fechaReservaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 190, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de reservación");
        Fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Costo");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        numeroPersonasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroPersonasTxtActionPerformed(evt);
            }
        });
        Fondo.add(numeroPersonasTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 190, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora de reservación");
        Fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        horaReservaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(horaReservaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 190, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Disponibilidad");
        Fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre del cliente");
        Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Numero de personas");
        Fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));
        Fondo.add(nombreClienteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 190, 40));
        Fondo.add(estadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 190, 40));
        Fondo.add(costoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 190, 40));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void numeroPersonasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroPersonasTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroPersonasTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton confirmarBtn;
    private javax.swing.JTextField costoTxt;
    private javax.swing.JTextField estadoTxt;
    private javax.swing.JComboBox<String> fechaReservaCB;
    private javax.swing.JComboBox<String> horaReservaCB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel mesa1;
    private Control.PanelRound mesa1P;
    private javax.swing.JLabel mesa2;
    private Control.PanelRound mesa2P;
    private javax.swing.JLabel mesa3;
    private Control.PanelRound mesa3P;
    private javax.swing.JLabel mesa4;
    private Control.PanelRound mesa4P;
    private javax.swing.JLabel mesa5;
    private Control.PanelRound mesa5P;
    private javax.swing.JLabel mesa6;
    private Control.PanelRound mesa6P;
    private javax.swing.JLabel mesa7;
    private Control.PanelRound mesa7P;
    private javax.swing.JLabel mesa8;
    private Control.PanelRound mesa8P;
    private javax.swing.JLabel mesa9;
    private Control.PanelRound mesa9P;
    private Control.PanelRound mesasPanel;
    private javax.swing.JTextField nombreClienteTxt;
    private javax.swing.JTextField numeroPersonasTxt;
    private Control.PanelRound tituloPanel;
    // End of variables declaration//GEN-END:variables
}
